import * as THREE from 'three';
const materials={cube:new THREE.MeshStandardMaterial({color:0xd96c4f,roughness:.55}),cone:new THREE.MeshStandardMaterial({color:0xe0b04f,roughness:.48}),cylinder:new THREE.MeshStandardMaterial({color:0x68a991,roughness:.5})};
export class TargetSystem extends THREE.Group{
 constructor({spawnDelay=2,maxTargets=6,bounds={x:4,y:2.5,z:5},onHit=()=>{}}={}){super();this.name='TargetSystem';this.spawnDelay=spawnDelay;this.maxTargets=maxTargets;this.bounds=bounds;this.onHit=onHit;this.targets=[];this.effects=[];this.elapsed=0;this.audioContext=null}
 update(delta,projectiles=[]){this.elapsed+=delta;if(this.elapsed>=this.spawnDelay){this.elapsed=0;if(this.targets.length<this.maxTargets)this.spawnRandomTarget()}for(const projectile of projectiles)this.checkProjectile(projectile);this.updateEffects(delta)}
 spawnRandomTarget(){const type=['cube','cone','cylinder'][Math.floor(Math.random()*3)],target=this.createTarget(type);target.position.set(THREE.MathUtils.randFloat(-this.bounds.x,this.bounds.x),THREE.MathUtils.randFloat(.7,this.bounds.y),THREE.MathUtils.randFloat(-this.bounds.z,-1));this.targets.push(target);this.add(target);return target}
 createTarget(type){const geometries={cube:new THREE.BoxGeometry(.65,.65,.65),cone:new THREE.ConeGeometry(.42,.9,20),cylinder:new THREE.CylinderGeometry(.42,.42,.8,20)};const target=new THREE.Mesh(geometries[type],materials[type].clone());target.name=`Target-${type}`;target.castShadow=true;target.receiveShadow=true;target.userData={target:true,type,radius:type==='cone'?.55:.48};return target}
 checkProjectile(projectile){if(!projectile?.position||projectile.userData?.spent)return false;for(const target of this.targets)if(projectile.position.distanceTo(target.position)<=target.userData.radius){this.impact(target,projectile);return true}return false}
 impact(target,projectile){if(!target.parent)return;projectile.userData.spent=true;this.createImpactEffect(target.position);this.playImpactSound();this.onHit({target,projectile,type:target.userData.type});this.removeTarget(target)}
 removeTarget(target){const index=this.targets.indexOf(target);if(index!==-1)this.targets.splice(index,1);this.remove(target);target.geometry.dispose();target.material.dispose()}
 createImpactEffect(position){const effect=new THREE.Group();effect.position.copy(position);effect.userData={life:.45,particles:[]};for(let i=0;i<14;i++){const particle=new THREE.Mesh(new THREE.SphereGeometry(.035,6,4),new THREE.MeshBasicMaterial({color:0xffd36b}));particle.userData.velocity=new THREE.Vector3(THREE.MathUtils.randFloatSpread(3),THREE.MathUtils.randFloat(.5,3),THREE.MathUtils.randFloatSpread(3));effect.userData.particles.push(particle);effect.add(particle)}this.add(effect);this.effects.push(effect)}
 updateEffects(delta){for(let i=this.effects.length-1;i>=0;i--){const effect=this.effects[i];effect.userData.life-=delta;for(const particle of effect.userData.particles){particle.userData.velocity.y-=7*delta;particle.position.addScaledVector(particle.userData.velocity,delta)}if(effect.userData.life<=0){this.remove(effect);effect.userData.particles.forEach(p=>{p.geometry.dispose();p.material.dispose()});this.effects.splice(i,1)}}}
 playImpactSound(){const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return;this.audioContext??=new AudioContextClass();if(this.audioContext.state==='suspended')this.audioContext.resume();const oscillator=this.audioContext.createOscillator(),gain=this.audioContext.createGain(),now=this.audioContext.currentTime;oscillator.type='triangle';oscillator.frequency.setValueAtTime(520,now);oscillator.frequency.exponentialRampToValueAtTime(160,now+.12);gain.gain.setValueAtTime(.18,now);gain.gain.exponentialRampToValueAtTime(.001,now+.12);oscillator.connect(gain).connect(this.audioContext.destination);oscillator.start();oscillator.stop(now+.12)}
}
